id: P004144
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:56:06.507629
source_metadata:
  id: bdr:W1KG24974
  title: བོད་སྨན་འདུལ་སྦྱོང་རིག་པ།
  author: ''
  volumes:
    00db10d219c744a3bde7096d6387e775:
      image_group_id: I1KG24976
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
